const products = [
  {
    name: 'Chaussure noire',
    price: 49.99,
    image: '/images/chaus-D.jpg',
    category: 'chaussures',
    description: 'Chaussures élégantes pour toutes occasions',
    countInStock: 10,
  },
  {
    name: 'Robe rouge',
    price: 59.99,
    image: '/images/fonds.jpg',
    category: 'vêtements',
    description: 'Robe rouge chic et confortable',
    countInStock: 5,
  },
  {
    name: 'Montre classique',
    price: 199.99,
    image: '/images/montre1.jpg',
    category: 'accessoires',
    description: 'Montre en acier inoxydable élégante',
    countInStock: 7,
  },
  {
    name: 'Tasse à café en céramique',
    price: 9.99,
    image: '/images/IMG-20250508-WA0072.jpg',
    category: 'maison',
    description: 'Tasse idéale pour le café du matin',
    countInStock: 20,
  },
  {
    name: 'Imprimante laser',
    price: 149.99,
    image: '/images/IMG-20250508-WA0058.jpg',
    category: 'électronique',
    description: 'Imprimante laser rapide et efficace',
    countInStock: 3,
  },
  {
    name: 'Perruque Afro',
    price: 89.99,
    image: '/images/perruque9.jpg',
    category: 'beauté',
    description: 'Perruque de haute qualité, naturelle',
    countInStock: 8,
  },
  {
    name: 'Casque audio Bluetooth',
    price: 79.99,
    image: '/images/casque-aud.jpg',
    category: 'électronique',
    description: 'Casque sans fil avec son HD',
    countInStock: 15,
  },
  {
    name: 'Crème hydratante visage',
    price: 24.99,
    image: '/images/creme.jpg',
    category: 'beauté',
    description: 'Crème hydratante pour tous types de peau',
    countInStock: 30,
  },
  {
    name: 'Tableau abstrait',
    price: 120.0,
    image: '/images/tableau4.jpg',
    category: 'décoration',
    description: 'Tableau moderne pour salon ou bureau',
    countInStock: 6,
  },
  {
    name: 'Cuisinière électrique',
    price: 399.99,
    image: '/images/IMG-20250508-WA0067.jpg',
    category: 'électroménager',
    description: 'Cuisinière 4 feux avec four intégré',
    countInStock: 4,
  },
  {
    name: 'Machine à laver',
    price: 499.99,
    image: '/images/machine-laver.jpg',
    category: 'électroménager',
    description: 'Machine à laver efficace et silencieuse',
    countInStock: 2,
  },
  {
    name: 'Micro-ondes multifonctions',
    price: 199.99,
    image: '/images/micro-ondes.jpg',
    category: 'électroménager',
    description: 'Micro-ondes avec plusieurs programmes',
    countInStock: 5,
  },
  {
    name: 'Chaussures de sport',
    price: 69.99,
    image: '/images/chaussures-sport.jpg',
    category: 'chaussures',
    description: 'Chaussures légères pour le sport et loisirs',
    countInStock: 12,
  },
  {
    name: 'Chemise homme',
    price: 29.99,
    image: '/images/chemise-homme.jpg',
    category: 'vêtements',
    description: 'Chemise confortable pour homme',
    countInStock: 14,
  },
  {
    name: 'Haut femme',
    price: 25.99,
    image: '/images/haut-femme.jpg',
    category: 'vêtements',
    description: 'Haut élégant pour femme',
    countInStock: 9,
  },
  {
    name: 'Parfum floral',
    price: 59.99,
    image: '/images/parfum-floral.jpg',
    category: 'beauté',
    description: 'Parfum avec notes florales fraîches',
    countInStock: 18,
  },
  {
    name: 'Sac à main en cuir',
    price: 99.99,
    image: '/images/sac-cuir.jpg',
    category: 'accessoires',
    description: 'Sac élégant en cuir véritable',
    countInStock: 7,
  },
  {
    name: 'Lunettes de soleil',
    price: 49.99,
    image: '/images/lunettes-soleil.jpg',
    category: 'accessoires',
    description: 'Lunettes de soleil UV400',
    countInStock: 11,
  },
  {
    name: 'Baskets blanches',
    price: 59.99,
    image: '/images/baskets-blanches.jpg',
    category: 'chaussures',
    description: 'Baskets confortables pour tous les jours',
    countInStock: 16,
  },
  {
    name: 'Crème solaire SPF 50',
    price: 19.99,
    image: '/images/creme-solaire.jpg',
    category: 'beauté',
    description: 'Crème solaire haute protection',
    countInStock: 25,
  },
  // --- PRODUITS SUPPLÉMENTAIRES ---
...Array.from({ length: 53 }, (_, i) => ({
  id: 28 + i,
  name: `Produit ${i + 1}`,
  price: 20 + (i % 50),
  image: `/images/produit${i + 1}.jpg`,
  category: i % 2 === 0 ? "Divers" : "Maison",
  description: `Description du produit ${i + 1} à compléter.`
}))

]

export default products
